@baseUrl = http://localhost:3333


# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
    "name": "Rômulo Valentim",
    "email": "valentim.canejo@hotmail.com",
    "password": "123456"
}

###

# @name create_account
POST {{baseUrl}}/sessions
Content-Type: application/json

{
    "name": "Rômulo Valentim",
    "email": "valentim.canejo@hotmail.com",
    "password": "123456"
}